### ISSUE TITLE
Heroku meet erros on rails v4.2.3

### ISSUE THREAD

**Issue by kikikiblue** [Shopify/identity_cache#214]
Today I upgraded my apps on Heroku to rails version 4.2.3 
but I met this error 

```
Error message
NoMethodError: undefined method `fetch_value' for #<Hash:0x007f6ca15c11a0>

Sample stack trace (show Rails)
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb: 107:in `block in set_embedded_association'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb: 107:in `each'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb: 107:in `set_embedded_association'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb:  95:in `block in record_from_coder'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb:  95:in `each'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb:  95:in `record_from_coder'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb:  30:in `block in fetch_by_id'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb: 154:in `require_if_necessary'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb:  27:in `fetch_by_id'
…s/identity_cache-0.2.5/lib/identity_cache/
query_api.rb:  44:in `fetch'
               /app/app/controllers/
steps_controller.rb: 227:in `group_member'
```

and steps_controller line 227 is like this. 
```
group = Group.fetch params[:group_id]
```

this error is only occurred on Heroku. 
It was ok on rails v4.1.10 + identity_cache v0.2.2 on Heroku. 
it is fine on my local machine with rails v4.2.3 + identity_cache v0.2.5
 
what is the problem of this?

**Comment by kikikiblue** [comment]
It works well with rails version 4.1.12 on Heroku.

**Comment by kikikiblue** [comment]
Sorry. it happened because I did not flush the memory. 
It works well now with rails v4.2.3
